version: '3.9'
services:
  db:
    container_name: pokemon-db
    image: postgres
    restart: always
    ports:
      - '${POSTGRES_PORT}:5432'
    healthcheck:
      test:
        ['CMD-SHELL', 'pg_isready', '-q', '-d', 'postgres', '-U', 'postgres']
      interval: 3s
      timeout: 3s
      retries: 10
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    build: .
    container_name: pokemon-web
    ports:
      - '${PORT}:8080'
    depends_on:
      db:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
    environment:
      POSTGRES_HOST: pokemon-db
      PORT: ${PORT}
      HOST: ${HOST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PORT: ${POSTGRES_PORT}
      MIKRO_ORM_CLI_USE_TS_NODE: false
  migration:
    build: .
    command: sh -c 'echo "running migrations"; node node_modules/.bin/mikro-orm migration:fresh --seed; echo "migrations finised"'
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_HOST: pokemon-db
      PORT: ${PORT}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PORT: ${POSTGRES_PORT}
      MIKRO_ORM_CLI_USE_TS_NODE: false
volumes:
  pgdata:
